name: Update Helm Chart

on:
  push:
    branches:
      - main

jobs:

  sync:
    permissions:
      contents: write

    runs-on: self-hosted
    env:
      # github-releases: coder/code-server
      CODER_VERSION: 'v4.107.1'

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v6

      - name: Clone source repo
        run: |
          git clone --depth 1 --branch $CODER_VERSION https://github.com/coder/code-server.git source

      - name: Copy helm-chart folder
        run: |
          rm -rf charts
          mkdir -p charts
          cp -r source/ci/helm-chart charts/code-server
          rm -rf source

      - name: Commit and push changes
        run: |
          set -ex;
          git config user.name "Forgejo Actions"
          git config user.email "actions@git.kr-t.de"
          git add charts
          git commit -m "Update helm-chart to tag $CODER_VERSION" || echo "No changes to commit"
          git push
          git fetch --prune --prune-tags --all
          git tag --list
          git tag -a $CODER_VERSION -m "Version $CODER_VERSION release" || echo "tag allready present"
          git push origin $CODER_VERSION || echo "No need to push"
