name: Update Helm Chart

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      CODER_VERSION: 'v4.101.0'

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Clone source repo
        run: |
          git clone --depth 1 --branch $CODER_VERSION https://github.com/coder/code-server.git source

      - name: Copy helm-chart folder
        run: |
          rm -rf charts
          mkdir -p charts
          cp -r source/ci/helm-chart charts/code-server
          rm -rf source

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add charts
          git commit -m "Update helm-chart to tag ${{ github.event.inputs.tag }}" || echo "No changes to commit"
          git push
